// Package aisdk provides a clean, idiomatic Go AI SDK with a configure-once workflow
// and provider-local model tiers.
//
// Configure once, use everywhere:
//
//	// config/ai.go  (generated by: aisdk init)
//	func init() {
//	    aisdk.Configure(&aisdk.Config{...})
//	}
//
//	// main.go
//	import _ "yourapp/config"  // just this one import
//
//	func main() {
//	    result, _ := aisdk.GenerateText(ctx, aisdk.TextParams{
//	        Model: "smart",
//	        Prompt: "Hello!",
//	    })
//	}
package aisdk

import (
	"context"
	"encoding/json"
	"fmt"
)

// TextParams holds parameters for GenerateText and StreamText calls.
type TextParams struct {
	Model    string
	System   string
	Prompt   string
	Messages []Message
	// Tools accepts both client-side tools (Executable) and provider-native
	// tools (BuiltinTool, e.g. &aisdk.WebSearch{}) in a single slice. Each is
	// dispatched to the correct request field automatically.
	Tools       []Tool
	Temperature *float64
	MaxTokens   *int
}

// ObjectParams holds parameters for GenerateObject calls.
type ObjectParams struct {
	Model       string
	System      string
	Prompt      string
	Messages    []Message
	Temperature *float64
	MaxTokens   *int
}

// --- Package-level functions (use the global default App) ---

// GenerateText performs a one-shot text generation using the default App.
// Configure the default App with Configure() or import your config package.
func GenerateText(ctx context.Context, params TextParams) (*Response, error) {
	app, err := DefaultApp()
	if err != nil {
		return nil, err
	}
	return app.GenerateText(ctx, params)
}

// StreamText performs a streaming text generation using the default App.
func StreamText(ctx context.Context, params TextParams) (*Stream, error) {
	app, err := DefaultApp()
	if err != nil {
		return nil, err
	}
	return app.StreamText(ctx, params)
}

// Quick creates an inline agent for one-off usage using the default App.
// Returns ErrNotConfigured if Configure has not been called.
//
//	agent, err := aisdk.Quick(aisdk.AgentConfig{
//	    Instructions: "You are a code reviewer.",
//	})
//	if err != nil { return err }
//	result, err := agent.Prompt(ctx, "Review this code...")
func Quick(config AgentConfig) (*BaseAgent, error) {
	app, err := DefaultApp()
	if err != nil {
		return nil, err
	}
	return QuickWithApp(app, config), nil
}

// --- App-level methods (for explicit App usage) ---

// GenerateText performs a one-shot text generation on a specific App.
func (a *App) GenerateText(ctx context.Context, params TextParams) (*Response, error) {
	textModel, providerName, modelName, err := a.GetTextModel(params.Model)
	if err != nil {
		return nil, err
	}

	messages := make([]Message, 0, len(params.Messages)+1)
	messages = append(messages, params.Messages...)
	if params.Prompt != "" {
		messages = append(messages, User(params.Prompt))
	}

	req := &TextRequest{
		Model:       modelName,
		System:      params.System,
		Messages:    messages,
		Temperature: params.Temperature,
		MaxTokens:   params.MaxTokens,
	}

	if len(params.Tools) > 0 {
		req.Tools = ToolsToDefinitions(params.Tools)
		req.BuiltinTools = splitBuiltins(params.Tools)
	}

	result, err := withRetry(ctx, a.effectiveRetry(), func() (*TextResult, error) {
		return textModel.Generate(ctx, req)
	})
	if err != nil {
		return nil, err
	}

	return &Response{
		Text:         result.Content,
		FinishReason: result.FinishReason,
		Usage:        result.Usage,
		Provider:     providerName,
		Model:        modelName,
	}, nil
}

// StreamText performs a streaming text generation on a specific App.
func (a *App) StreamText(ctx context.Context, params TextParams) (*Stream, error) {
	textModel, providerName, modelName, err := a.GetTextModel(params.Model)
	if err != nil {
		return nil, err
	}

	messages := make([]Message, 0, len(params.Messages)+1)
	messages = append(messages, params.Messages...)
	if params.Prompt != "" {
		messages = append(messages, User(params.Prompt))
	}

	req := &TextRequest{
		Model:       modelName,
		System:      params.System,
		Messages:    messages,
		Temperature: params.Temperature,
		MaxTokens:   params.MaxTokens,
	}

	if len(params.Tools) > 0 {
		req.Tools = ToolsToDefinitions(params.Tools)
		req.BuiltinTools = splitBuiltins(params.Tools)
	}

	result, err := withRetry(ctx, a.effectiveRetry(), func() (*TextStreamResult, error) {
		return textModel.Stream(ctx, req)
	})
	if err != nil {
		return nil, err
	}

	wrappedCh := make(chan StreamEvent)
	go func() {
		defer close(wrappedCh)
		wrappedCh <- &StreamStart{Provider: providerName, Model: modelName}
		for event := range result.Events {
			wrappedCh <- event
		}
	}()

	return NewStream(wrappedCh), nil
}

// --- GenerateObject (generic, must be package-level) ---

// GenerateObject performs a text generation and parses the output into a typed struct.
// Uses the default App. For explicit App usage, use GenerateObjectWithApp.
func GenerateObject[T any](ctx context.Context, params ObjectParams) (*ObjectResponse[T], error) {
	app, err := DefaultApp()
	if err != nil {
		return nil, err
	}
	return GenerateObjectWithApp[T](ctx, app, params)
}

// GenerateObjectWithApp performs structured output generation on a specific App.
func GenerateObjectWithApp[T any](ctx context.Context, app *App, params ObjectParams) (*ObjectResponse[T], error) {
	textModel, providerName, modelName, err := app.GetTextModel(params.Model)
	if err != nil {
		return nil, err
	}

	messages := make([]Message, 0, len(params.Messages)+1)
	messages = append(messages, params.Messages...)
	if params.Prompt != "" {
		messages = append(messages, User(params.Prompt+"\n\nRespond with valid JSON only."))
	}

	var zero T
	schema := GenerateJSONSchema(zero)

	req := &TextRequest{
		Model:       modelName,
		System:      params.System,
		Messages:    messages,
		Temperature: params.Temperature,
		MaxTokens:   params.MaxTokens,
		ResponseFormat: &ResponseFormat{
			Type:       "json_schema",
			JSONSchema: schema,
		},
	}

	result, err := textModel.Generate(ctx, req)
	if err != nil {
		return nil, err
	}

	// Strip markdown code fences if the model wraps the JSON
	text := stripJSONCodeFence(result.Content)

	var obj T
	if err := json.Unmarshal([]byte(text), &obj); err != nil {
		return nil, fmt.Errorf("aisdk: failed to parse structured output: %w", err)
	}

	return &ObjectResponse[T]{
		Object:       obj,
		Text:         text,
		FinishReason: result.FinishReason,
		Usage:        result.Usage,
		Provider:     providerName,
		Model:        modelName,
	}, nil
}

// QuickWithApp creates an inline agent on a specific App.
func QuickWithApp(app *App, config AgentConfig) *BaseAgent {
	agent := NewBaseAgentWithApp(app, config)
	return &agent
}
