// Command aisdk provides scaffolding tools for the aisdk-go SDK.
//
// Install:
//
//	go install github.com/sadhakbj/aisdk-go/cmd/aisdk@latest
//
// Usage:
//
//	aisdk init                    # Generate config/ai.go in current project
//	aisdk init --dir myconfig     # Generate in a custom directory
//	aisdk new agent SalesCoach    # Scaffold a new agent file
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	switch os.Args[1] {
	case "init":
		cmdInit()
	case "new":
		if len(os.Args) < 4 {
			fmt.Println("Usage: aisdk new agent <Name>")
			os.Exit(1)
		}
		if os.Args[2] == "agent" {
			cmdNewAgent(os.Args[3])
		} else {
			fmt.Printf("Unknown resource type: %s\n", os.Args[2])
			os.Exit(1)
		}
	case "help", "--help", "-h":
		printUsage()
	default:
		fmt.Printf("Unknown command: %s\n", os.Args[1])
		printUsage()
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Println(`aisdk - AI SDK for Go scaffolding tool

Usage:
  aisdk init                    Generate config/ai.go for your module
  aisdk init --dir <path>       Generate config in a custom directory
  aisdk new agent <Name>        Scaffold a new agent file in agents/

Examples:
  aisdk init
  aisdk new agent SalesCoach
  aisdk new agent CodeReviewer

Install:
  go install github.com/sadhakbj/aisdk-go/cmd/aisdk@latest`)
}

func cmdInit() {
	dir := "config"
	for i, arg := range os.Args {
		if arg == "--dir" && i+1 < len(os.Args) {
			dir = os.Args[i+1]
		}
	}

	// Detect the module name
	moduleName := detectModuleName()

	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Printf("Error creating directory %s: %v\n", dir, err)
		os.Exit(1)
	}

	filePath := filepath.Join(dir, "ai.go")
	if _, err := os.Stat(filePath); err == nil {
		fmt.Printf("File %s already exists. Overwrite? (y/N): ", filePath)
		var answer string
		fmt.Scanln(&answer)
		if strings.ToLower(answer) != "y" {
			fmt.Println("Aborted.")
			return
		}
	}

	content := generateConfigFile(dir, moduleName)

	if err := os.WriteFile(filePath, []byte(content), 0o644); err != nil {
		fmt.Printf("Error writing %s: %v\n", filePath, err)
		os.Exit(1)
	}

	fmt.Printf("Created %s\n", filePath)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Printf("  1. Set your API keys as environment variables:\n")
	fmt.Printf("     export OPENAI_API_KEY=sk-...\n")
	fmt.Printf("     export ANTHROPIC_API_KEY=sk-ant-...\n")
	fmt.Println()
	fmt.Printf("  2. Import the config in your main.go:\n")
	if moduleName != "" {
		fmt.Printf("     import _ \"%s/%s\"\n", moduleName, dir)
	} else {
		fmt.Printf("     import _ \"yourmodule/%s\"\n", dir)
	}
	fmt.Println()
	fmt.Printf("  3. Use the SDK anywhere:\n")
	fmt.Printf("     result, err := aisdk.GenerateText(ctx, aisdk.TextParams{...})\n")
}

func cmdNewAgent(name string) {
	dir := "agents"
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Printf("Error creating directory %s: %v\n", dir, err)
		os.Exit(1)
	}

	fileName := toSnakeCase(name) + ".go"
	filePath := filepath.Join(dir, fileName)

	if _, err := os.Stat(filePath); err == nil {
		fmt.Printf("File %s already exists.\n", filePath)
		os.Exit(1)
	}

	content := generateAgentFile(name)

	if err := os.WriteFile(filePath, []byte(content), 0o644); err != nil {
		fmt.Printf("Error writing %s: %v\n", filePath, err)
		os.Exit(1)
	}

	fmt.Printf("Created %s\n", filePath)
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Printf("  agent := agents.New%s()\n", name)
	fmt.Printf("  result, err := agent.Prompt(ctx, \"...\")\n")
}

func generateConfigFile(pkgName, moduleName string) string {
	pkg := filepath.Base(pkgName)
	return fmt.Sprintf(`// Package %s configures the AI SDK.
// Generated by: aisdk init
//
// Import this package in your main.go to activate the configuration:
//
//   import _ "%s/%s"
//
// Each provider knows its own models — no model mapping needed.
// Use built-in aliases anywhere: "smart", "fast", "default"
//
//   aisdk.GenerateText(ctx, aisdk.TextParams{Model: "smart", Prompt: "..."})
package %s

import (
	"os"

	"github.com/sadhakbj/aisdk-go"
	"github.com/sadhakbj/aisdk-go/providers/anthropic"
	"github.com/sadhakbj/aisdk-go/providers/openai"
)

func init() {
	aisdk.Configure(&aisdk.Config{
		// Providers — credentials (and optional base URL) only.
		// Each provider defines its own models internally:
		//   "smart"   → provider's most capable model
		//   "fast"    → provider's cheapest/fastest model
		//   "default" → provider's default model
		Providers: map[string]aisdk.ProviderConfig{
			"openai": &openai.Config{
				APIKey: os.Getenv("OPENAI_API_KEY"),
			},
			"anthropic": &anthropic.Config{
				APIKey: os.Getenv("ANTHROPIC_API_KEY"),
			},
		},

		// Default provider used when no provider is specified.
		Default: "openai",

		// Conversation store — defaults to in-memory.
		// Swap with your own ConversationStore implementation for persistence.
		// ConversationStore: myRedisStore,
	})
}
`, pkg, moduleName, pkgName, pkg)
}

func generateAgentFile(name string) string {
	return fmt.Sprintf(`package agents

import (
	"context"
	"time"

	"github.com/sadhakbj/aisdk-go"
)

// %s is an AI agent.
// Generated by: aisdk new agent %s
type %s struct {
	aisdk.BaseAgent
}

// New%s creates a new %s agent.
func New%s() *%s {
	return &%s{
		BaseAgent: aisdk.NewBaseAgent(aisdk.AgentConfig{
			Model:        "smart",
			Instructions: "You are a helpful assistant.",
			MaxSteps:     5,
			Temperature:  0.7,
			Timeout:      60 * time.Second,
			// Tools:     []aisdk.Tool{},
			// Middleware: []aisdk.Middleware{},
		}),
	}
}

// BeforePrompt is called before every prompt. Use it to inject context.
func (a *%s) BeforePrompt(ctx context.Context, p *aisdk.Prompt) {
	// Example: p.Prepend(aisdk.System("Extra context here"))
}
`, name, name, name, name, name, name, name, name, name)
}

func detectModuleName() string {
	// Try to read go.mod to find the module name
	data, err := os.ReadFile("go.mod")
	if err != nil {
		// Try parent directories
		dir, _ := os.Getwd()
		for {
			parent := filepath.Dir(dir)
			if parent == dir {
				break
			}
			dir = parent
			modFile := filepath.Join(dir, "go.mod")
			data, err = os.ReadFile(modFile)
			if err == nil {
				break
			}
		}
	}
	if data == nil {
		// Fall back to `go list`
		out, err := exec.Command("go", "list", "-m").Output()
		if err != nil {
			return ""
		}
		return strings.TrimSpace(string(out))
	}

	for line := range strings.SplitSeq(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimPrefix(line, "module ")
		}
	}
	return ""
}

func toSnakeCase(s string) string {
	var result []rune
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			result = append(result, '_')
		}
		result = append(result, unicode.ToLower(r))
	}
	return string(result)
}
